Repository craftcms/cms, pull requests merged in 2021-06, with the labels that each got.

#8043 Add single action buttons / Add horizontal separators to menu buttons in admin tables
  CHANGELOG-v3.7.md
  src/web/assets/admintable/README.md
  src/web/assets/admintable/dist/js/app.js
  src/web/assets/admintable/dist/js/app.js.map
  src/web/assets/admintable/dist/js/chunk-vendors.js.map
  src/web/assets/admintable/src/App.vue
  src/web/assets/admintable/src/js/components/AdminTableActionButton.vue
Labels: enhancement, ux :smile:

#8096 Add nvmrc file.
  .nvmrc
Labels: environmental

#9059 Fix phrasing: `up-to-date` → `up to date`
  src/console/controllers/MigrateController.php
  src/console/controllers/UpdateController.php
  src/db/MigrationManager.php
  src/templates/_components/widgets/Updates/body.html
  src/translations/ar/app.php
  src/translations/cs/app.php
  src/translations/da/app.php
  src/translations/de-CH/app.php
  src/translations/de/app.php
  src/translations/en-GB/app.php
  src/translations/en/app.php
  src/translations/es/app.php
  src/translations/fa/app.php
  src/translations/fr-CA/app.php
  src/translations/fr/app.php
  src/translations/he/app.php
  src/translations/hu/app.php
  src/translations/it/app.php
  src/translations/ja/app.php
  src/translations/ko/app.php
  src/translations/nb/app.php
  src/translations/nl/app.php
  src/translations/nn/app.php
  src/translations/pl/app.php
  src/translations/pt/app.php
  src/translations/ru/app.php
  src/translations/sk/app.php
  src/translations/sv/app.php
  src/translations/tr/app.php
  src/translations/zh/app.php
  src/web/assets/updates/UpdatesAsset.php
  src/web/assets/updates/dist/UpdatesUtility.min.js
  src/web/assets/updates/dist/UpdatesUtility.min.js.map
  src/web/assets/updates/src/UpdatesUtility.js
  src/web/assets/updateswidget/UpdatesWidgetAsset.php
  src/web/assets/updateswidget/dist/UpdatesWidget.min.js
  src/web/assets/updateswidget/dist/UpdatesWidget.min.js.map
  src/web/assets/updateswidget/src/UpdatesWidget.js
  src/web/twig/TemplateLoader.php
Labels: bug

#9060 Improve `backup` phrasing
  src/console/controllers/BackupTrait.php
Labels: bug
