Repository craftcms/cms, pull requests merged in 2022-06, with the labels that each got.

#11202 Add disclosure attributes to toggle buttons and darken status expand text color
  src/base/Element.php
  src/templates/_elements/toolbar.twig
  src/templates/_layouts/elementindex.twig
  src/translations/en/app.php
  src/web/assets/admintable/dist/css/app.css
  src/web/assets/admintable/dist/css/app.css.map
  src/web/assets/admintable/dist/js/app.js
  src/web/assets/admintable/dist/js/app.js.map
  src/web/assets/admintable/dist/manifest.json
  src/web/assets/cp/dist/cp.js
  src/web/assets/cp/dist/cp.js.map
  src/web/assets/cp/dist/css/cp.css
  src/web/assets/cp/dist/css/cp.css.map
  src/web/assets/cp/src/css/_main.scss
  src/web/assets/cp/src/js/BaseElementIndex.js
Labels: accessibility :bust_in_silhouette:

#11200 Enable keyboard users to expand and collapse element children in Structure sections and categories
  CHANGELOG-WIP.md
  src/templates/_elements/tableview/elements.twig
  src/translations/en/app.php
  src/web/assets/cp/CpAsset.php
  src/web/assets/cp/dist/cp.js
  src/web/assets/cp/dist/cp.js.map
  src/web/assets/cp/dist/css/cp.css
  src/web/assets/cp/dist/css/cp.css.map
  src/web/assets/cp/src/css/_main.scss
  src/web/assets/cp/src/js/StructureTableSorter.js
  src/web/assets/cp/src/js/TableElementIndexView.js
Labels: accessibility :bust_in_silhouette:

#11358 Only enable slideout sidebar focus trap when toggled via button
  CHANGELOG.md
  src/web/assets/cp/dist/cp.js
  src/web/assets/cp/dist/cp.js.map
  src/web/assets/cp/src/js/CpScreenSlideout.js
Labels: accessibility :bust_in_silhouette:

#11217 Dashboard a11y updates
  CHANGELOG-WIP.md
  src/templates/_components/widgets/Updates/body.twig
  src/templates/dashboard/_index.twig
  src/translations/en/app.php
  src/web/assets/cp/dist/css/cp.css
  src/web/assets/cp/dist/css/cp.css.map
  src/web/assets/cp/src/css/_main.scss
  src/web/assets/dashboard/dist/Dashboard.js
  src/web/assets/dashboard/dist/Dashboard.js.map
  src/web/assets/dashboard/dist/css/Dashboard.css
  src/web/assets/dashboard/dist/css/Dashboard.css.map
  src/web/assets/dashboard/src/Dashboard.js
  src/web/assets/dashboard/src/dashboard.scss
  src/web/assets/updateswidget/dist/UpdatesWidget.js
  src/web/assets/updateswidget/dist/UpdatesWidget.js.map
  src/web/assets/updateswidget/src/UpdatesWidget.js
Labels: accessibility :bust_in_silhouette:

#11371 Fix bug blocking keyboard users from accessing video controls
  CHANGELOG.md
  src/web/assets/cp/dist/cp.js
  src/web/assets/cp/dist/cp.js.map
  src/web/assets/cp/dist/css/cp.css
  src/web/assets/cp/dist/css/cp.css.map
  src/web/assets/cp/src/css/_cp.scss
  src/web/assets/cp/src/js/PreviewFileModal.js
  src/web/assets/cp/src/js/UI.js
  src/web/assets/garnish/dist/garnish.js
  src/web/assets/garnish/dist/garnish.js.map
  src/web/assets/garnish/src/Garnish.js
Labels: accessibility :bust_in_silhouette:, 🐞 bug

#11306 Matrix field a11y improvements
  CHANGELOG-WIP.md
  src/base/Field.php
  src/base/FieldInterface.php
  src/fieldlayoutelements/BaseField.php
  src/fieldlayoutelements/CustomField.php
  src/fields/Matrix.php
  src/helpers/Cp.php
  src/templates/_components/fieldtypes/Matrix/input.twig
  src/web/assets/admintable/dist/css/app.css
  src/web/assets/admintable/dist/js/app.js
  src/web/assets/admintable/dist/js/app.js.map
  src/web/assets/admintable/dist/manifest.json
  src/web/assets/cp/dist/css/cp.css
  src/web/assets/cp/dist/css/cp.css.map
  src/web/assets/cp/src/css/_main.scss
  src/web/assets/matrix/dist/MatrixInput.js
  src/web/assets/matrix/dist/MatrixInput.js.map
  src/web/assets/matrix/src/MatrixInput.js
  src/web/assets/pluginstore/dist/css/app.css
  src/web/assets/pluginstore/dist/css/app.css.map
Labels: accessibility :bust_in_silhouette:

#11323 Toggle element selector modal sidebar for small screens and zoom
  CHANGELOG-WIP.md
  packages/craftcms-sass/_mixins.scss
  src/templates/_elements/modalbody.twig
  src/templates/_layouts/components/crumbs.twig
  src/web/assets/cp/dist/cp.js
  src/web/assets/cp/dist/cp.js.map
  src/web/assets/cp/dist/css/cp.css
  src/web/assets/cp/dist/css/cp.css.map
  src/web/assets/cp/src/css/_cp.scss
  src/web/assets/cp/src/css/_main.scss
  src/web/assets/cp/src/js/BaseElementSelectorModal.js
  src/web/assets/cp/src/js/CP.js
  src/web/assets/cp/src/js/UI.js
  src/web/assets/craftsupport/dist/css/CraftSupportWidget.css.map
  src/web/assets/dashboard/dist/css/Dashboard.css.map
  src/web/assets/edittransform/dist/css/transforms.css.map
  src/web/assets/edituser/dist/css/AccountSettingsForm.css.map
  src/web/assets/edituser/dist/css/profile.css.map
  src/web/assets/garnish/dist/garnish.js
  src/web/assets/garnish/dist/garnish.js.map
  src/web/assets/garnish/src/Modal.js
  src/web/assets/generalsettings/dist/css/rebrand.css.map
  src/web/assets/graphiql/dist/css/graphiql.css
  src/web/assets/graphiql/dist/css/graphiql.css.map
  src/web/assets/installer/dist/css/install.css
  src/web/assets/installer/dist/css/install.css.map
  src/web/assets/login/dist/css/login.css
  src/web/assets/login/dist/css/login.css.map
  src/web/assets/money/dist/css/Money.css.map
  src/web/assets/plugins/dist/css/PluginManager.css
  src/web/assets/plugins/dist/css/PluginManager.css.map
  src/web/assets/pluginstore/dist/css/app.css
  src/web/assets/pluginstore/dist/css/app.css.map
  src/web/assets/pluginstoreoauth/dist/css/PluginStoreOauthCallback.css.map
  src/web/assets/routes/dist/css/routes.css
  src/web/assets/routes/dist/css/routes.css.map
  src/web/assets/systemmessages/dist/css/system_messages.css
  src/web/assets/systemmessages/dist/css/system_messages.css.map
  src/web/assets/updater/dist/css/Updater.css.map
  src/web/assets/updates/dist/css/UpdatesUtility.css.map
  src/web/assets/upgrade/dist/css/UpgradeUtility.css
  src/web/assets/upgrade/dist/css/UpgradeUtility.css.map
  src/web/assets/userpermissions/dist/css/UserPermissions.css.map
  src/web/assets/utilities/dist/css/utilities.css.map
Labels: enhancement, accessibility :bust_in_silhouette:

#11414 Custom select a11y
  src/templates/_elements/toolbar.twig
  src/web/assets/cp/dist/cp.js
  src/web/assets/cp/dist/cp.js.map
  src/web/assets/garnish/dist/garnish.js
  src/web/assets/garnish/dist/garnish.js.map
  src/web/assets/garnish/src/CustomSelect.js
  src/web/assets/garnish/src/Garnish.js
  src/web/assets/garnish/src/MenuBtn.js
Labels: accessibility :bust_in_silhouette:

#11445 Make keyed data accessible with `ActiveFixture`
  CHANGELOG-WIP.md
  src/test/ActiveFixture.php
Labels: testing ✅
