Repository craftcms/cms, pull requests merged in 2022-04, with the labels that each got.

#10862 Fix preferSites example in description.
  src/elements/db/ElementQueryInterface.php
Labels: docs :notebook_with_decorative_cover:

#10896 [4.x] Address card label/actions alignment
  CHANGELOG.md
  src/web/assets/cp/dist/css/cp.css
  src/web/assets/cp/dist/css/cp.css.map
  src/web/assets/cp/src/css/_main.scss
Labels: ui :eyes:, 🐞 bug

#10660 Search UI
  CHANGELOG-WIP.md
  CHANGELOG.md
  src/templates/_elements/toolbar.twig
  src/translations/en/app.php
  src/web/assets/cp/dist/cp.js
  src/web/assets/cp/dist/cp.js.map
  src/web/assets/cp/dist/css/cp.css
  src/web/assets/cp/dist/css/cp.css.map
  src/web/assets/cp/src/css/_main.scss
  src/web/assets/cp/src/js/BaseElementIndex.js
Labels: accessibility :bust_in_silhouette:

#10955 [4.x] Fixed squashed avatars in element index tables
  CHANGELOG.md
  src/web/assets/cp/dist/css/cp.css
  src/web/assets/cp/dist/css/cp.css.map
  src/web/assets/cp/src/css/_main.scss
Labels: 🐞 bug
