Repository craftcms/cms, pull requests merged in 2022-09, with the labels that each got.

#11888 Add extra date range condition rule options
  CHANGELOG-WIP.md
  src/base/conditions/BaseDateRangeConditionRule.php
  src/enums/DateRangeType.php
  src/helpers/DateRange.php
  src/helpers/DateTimeHelper.php
  src/translations/en/app.php
  src/web/assets/cp/CpAsset.php
  tests/unit/conditions/rules/DateCreatedConditionRuleTest.php
  tests/unit/helpers/DateRangeHelperTest.php
  tests/unit/helpers/DateTimeHelperTest.php
Labels: enhancement

#11844 Sticky content footer + move element actions into it
  CHANGELOG-WIP.md
  src/templates/_components/elementactions/SetStatus/trigger.twig
  src/templates/_layouts/elementindex.twig
  src/web/assets/cp/dist/cp.js
  src/web/assets/cp/dist/cp.js.map
  src/web/assets/cp/dist/css/cp.css
  src/web/assets/cp/dist/css/cp.css.map
  src/web/assets/cp/src/css/_cp.scss
  src/web/assets/cp/src/js/BaseElementIndex.js
  src/web/assets/cp/src/js/CP.js
Labels: accessibility :bust_in_silhouette:, ui :eyes:

#11921 Add labels for new condition builder date options
  src/base/conditions/BaseDateRangeConditionRule.php
  src/translations/en/app.php
Labels: accessibility :bust_in_silhouette:
