Repository craftcms/cms, pull requests merged in 2022-03, with the labels that each got.

#10681 Improve notes field appearance
  src/controllers/ElementsController.php
  src/web/assets/admintable/dist/css/app.css
  src/web/assets/admintable/dist/js/app.js
  src/web/assets/admintable/dist/js/app.js.LICENSE.txt
  src/web/assets/admintable/dist/js/app.js.map
  src/web/assets/admintable/dist/manifest.json
  src/web/assets/cp/dist/css/cp.css
  src/web/assets/cp/dist/css/cp.css.map
  src/web/assets/cp/src/css/_cp.scss
  src/web/assets/graphiql/dist/graphiql.js
  src/web/assets/graphiql/dist/graphiql.js.map
  src/web/assets/pluginstore/dist/css/app.css
  src/web/assets/pluginstore/dist/css/app.css.map
  src/web/assets/pluginstore/dist/js/app.js
  src/web/assets/pluginstore/dist/js/app.js.map
  src/web/assets/pluginstoreoauth/dist/parseFragmentString.js.map
  src/web/assets/tailwindreset/dist/css/tailwind_reset.css.map
Labels: ui :eyes:

#10699 fix: doc-block typo
  src/web/Session.php
Labels: docs :notebook_with_decorative_cover:

#10686 Fix Safari Matrix block menu item appearance
  src/web/assets/cp/dist/css/cp.css
  src/web/assets/cp/dist/css/cp.css.map
  src/web/assets/cp/src/css/_main.scss
  src/web/assets/tailwindreset/dist/css/tailwind_reset.css.map
Labels: bug, ui :eyes:

#10737 Fix the position of the powered by logo
  src/web/assets/login/dist/css/login.css
  src/web/assets/login/dist/css/login.css.map
  src/web/assets/login/src/login.scss
Labels: bug
