Repository craftcms/cms, pull requests merged in 2022-10, with the labels that each got.

#11942 Refactor Listbox to use exclusive button group pattern
  CHANGELOG-WIP.md
  src/helpers/Cp.php
  src/web/assets/cp/dist/cp.js
  src/web/assets/cp/dist/cp.js.map
  src/web/assets/cp/dist/css/cp.css
  src/web/assets/cp/dist/css/cp.css.map
  src/web/assets/cp/src/css/_cp.scss
  src/web/assets/cp/src/css/_main.scss
  src/web/assets/cp/src/css/_preview.scss
  src/web/assets/cp/src/js/BaseElementIndex.js
  src/web/assets/cp/src/js/Listbox.js
  src/web/assets/cp/src/js/Preview.js
  src/web/assets/pluginstore/dist/css/app.css
  src/web/assets/pluginstore/dist/js/app.js
  src/web/assets/pluginstore/dist/js/app.js.map
Labels: accessibility :bust_in_silhouette:

#11945 Expose expanded/collapsed state for widget manager button
  CHANGELOG-WIP.md
  src/templates/dashboard/_index.twig
  src/web/assets/dashboard/dist/Dashboard.js
  src/web/assets/dashboard/dist/Dashboard.js.map
  src/web/assets/dashboard/src/Dashboard.js
Labels: accessibility :bust_in_silhouette:

#11952 Use list elements for Feed, Recent Entries, and Drafts widgets
  CHANGELOG-WIP.md
  src/templates/_components/widgets/Feed/body.twig
  src/templates/_components/widgets/RecentEntries/body.twig
  src/web/assets/dashboard/dist/css/Dashboard.css
  src/web/assets/dashboard/dist/css/Dashboard.css.map
  src/web/assets/dashboard/src/dashboard.scss
  src/widgets/MyDrafts.php
Labels: accessibility :bust_in_silhouette:

#11953 Fix incorrect aria-disabled state on rotate button in Preview modal
  CHANGELOG-WIP.md
  src/web/assets/cp/dist/cp.js
  src/web/assets/cp/dist/cp.js.map
  src/web/assets/cp/src/js/Preview.js
Labels: accessibility :bust_in_silhouette:, 🐞 bug

#11955 Fix clipped content in Craft Support widgets when text is zoomed to 200%
  CHANGELOG-WIP.md
  src/web/assets/cp/dist/css/cp.css
  src/web/assets/cp/dist/css/cp.css.map
  src/web/assets/cp/src/css/_main.scss
  src/web/assets/craftsupport/dist/css/CraftSupportWidget.css
  src/web/assets/craftsupport/dist/css/CraftSupportWidget.css.map
  src/web/assets/craftsupport/src/CraftSupportWidget.scss
Labels: accessibility :bust_in_silhouette:

#11963 Ensure primary action menu doesn't fall offscreen on small viewports
  CHANGELOG-WIP.md
  src/web/assets/cp/dist/css/cp.css
  src/web/assets/cp/dist/css/cp.css.map
  src/web/assets/cp/src/css/_cp.scss
  src/web/assets/garnish/dist/garnish.js
  src/web/assets/garnish/dist/garnish.js.map
  src/web/assets/garnish/src/DisclosureMenu.js
Labels: accessibility :bust_in_silhouette:

#11985 Manage focus for HUD components
  CHANGELOG-WIP.md
  src/web/assets/garnish/dist/garnish.js
  src/web/assets/garnish/dist/garnish.js.map
  src/web/assets/garnish/src/Garnish.js
  src/web/assets/garnish/src/HUD.js
Labels: accessibility :bust_in_silhouette:

#12078 Type error on image transform save
  src/controllers/ImageTransformsController.php
Labels: severity:normal, 🐞 bug
