Repository craftcms/cms, pull requests merged in 2022-05, with the labels that each got.

#11126 Make pagination arrows accessible to keyboard users
  CHANGELOG-WIP.md
  src/templates/_includes/pagination.twig
  src/templates/_layouts/elementindex.twig
  src/translations/en/app.php
  src/web/assets/cp/CpAsset.php
  src/web/assets/cp/dist/cp.js
  src/web/assets/cp/dist/cp.js.map
  src/web/assets/cp/dist/css/cp.css
  src/web/assets/cp/dist/css/cp.css.map
  src/web/assets/cp/src/css/_main.scss
  src/web/assets/cp/src/js/BaseElementIndex.js
  src/web/assets/pluginstore/dist/css/app.css
  src/web/assets/pluginstore/dist/css/app.css.map
  src/web/assets/pluginstore/dist/js/app.js
  src/web/assets/pluginstore/dist/js/app.js.map
Labels: accessibility :bust_in_silhouette:

#11172 Center customer support logos, update Partners alt text, and add disabled state to submit button
  src/templates/_components/widgets/CraftSupport/body.twig
  src/web/assets/craftsupport/dist/CraftSupportWidget.js
  src/web/assets/craftsupport/dist/CraftSupportWidget.js.map
  src/web/assets/craftsupport/dist/css/CraftSupportWidget.css
  src/web/assets/craftsupport/dist/css/CraftSupportWidget.css.map
  src/web/assets/craftsupport/src/CraftSupportWidget.js
  src/web/assets/craftsupport/src/CraftSupportWidget.scss
  src/web/assets/pluginstore/dist/css/app.css
  src/web/assets/pluginstore/dist/css/app.css.map
  src/web/assets/pluginstore/dist/js/app.js
  src/web/assets/pluginstore/dist/js/app.js.map
Labels: bug, accessibility :bust_in_silhouette:

#11169 Improve accessibility of sidebar toggle on mobile element index pages, darken sidebar headings
  CHANGELOG-WIP.md
  packages/craftcms-sass/_mixins.scss
  src/templates/_layouts/cp.twig
  src/web/assets/cp/dist/cp.js
  src/web/assets/cp/dist/cp.js.map
  src/web/assets/cp/dist/css/cp.css
  src/web/assets/cp/dist/css/cp.css.map
  src/web/assets/cp/src/css/_cp.scss
  src/web/assets/cp/src/css/_main.scss
  src/web/assets/cp/src/js/BaseElementIndex.js
  src/web/assets/cp/src/js/CP.js
  src/web/assets/craftsupport/dist/css/CraftSupportWidget.css.map
  src/web/assets/dashboard/dist/css/Dashboard.css.map
  src/web/assets/edittransform/dist/css/transforms.css.map
  src/web/assets/edituser/dist/css/AccountSettingsForm.css.map
  src/web/assets/edituser/dist/css/profile.css.map
  src/web/assets/generalsettings/dist/css/rebrand.css.map
  src/web/assets/graphiql/dist/css/graphiql.css.map
  src/web/assets/installer/dist/css/install.css.map
  src/web/assets/login/dist/css/login.css.map
  src/web/assets/money/dist/css/Money.css.map
  src/web/assets/plugins/dist/css/PluginManager.css.map
  src/web/assets/pluginstore/dist/css/app.css.map
  src/web/assets/pluginstoreoauth/dist/css/PluginStoreOauthCallback.css.map
  src/web/assets/routes/dist/css/routes.css.map
  src/web/assets/systemmessages/dist/css/system_messages.css.map
  src/web/assets/updater/dist/css/Updater.css.map
  src/web/assets/updates/dist/css/UpdatesUtility.css.map
  src/web/assets/upgrade/dist/css/UpgradeUtility.css.map
  src/web/assets/userpermissions/dist/css/UserPermissions.css.map
  src/web/assets/utilities/dist/css/utilities.css.map
Labels: accessibility :bust_in_silhouette:

#11267 Consistently use “deprecation warnings”
  CHANGELOG-WIP.md
  src/controllers/UtilitiesController.php
  src/services/Deprecator.php
  src/templates/_components/utilities/DeprecationErrors/index.twig
  src/translations/en/app.php
  src/views/debug/deprecated/detail.php
  tests/functional/PageRenderChecksCest.php
Labels: docs :notebook_with_decorative_cover:
