Repository craftcms/cms, pull requests merged in 2023-03, with the labels that each got.

#12751 Add overflow-y scroll to condition builder
  CHANGELOG-WIP.md
  CHANGELOG.md
  src/web/assets/cp/dist/cp.js
  src/web/assets/cp/dist/cp.js.map
  src/web/assets/cp/dist/css/cp.css
  src/web/assets/cp/dist/css/cp.css.map
  src/web/assets/cp/src/css/_main.scss
  src/web/assets/cp/src/js/BaseElementIndex.js
Labels: accessibility :bust_in_silhouette:

#12754 Use MultiFunctionBtn for Export button
  CHANGELOG-WIP.md
  CHANGELOG.md
  src/web/assets/cp/dist/cp.js
  src/web/assets/cp/dist/cp.js.map
  src/web/assets/cp/src/js/BaseElementIndex.js
  src/web/assets/garnish/dist/garnish.js
  src/web/assets/garnish/dist/garnish.js.map
  src/web/assets/garnish/src/MultiFunctionBtn.js
  src/web/assets/login/dist/login.js
  src/web/assets/login/dist/login.js.map
  src/web/assets/login/src/login.js
Labels: accessibility :bust_in_silhouette:

#12766 Fixes incorrect rendering of source path component
  CHANGELOG.md
  src/web/assets/cp/dist/css/cp.css
  src/web/assets/cp/dist/css/cp.css.map
  src/web/assets/cp/src/css/_main.scss
Labels: ui :eyes:, 🐞 bug

#12772 Wrap Quick Post checkboxes in fieldset element
  CHANGELOG-WIP.md
  CHANGELOG.md
  src/templates/_components/widgets/QuickPost/settings.twig
Labels: accessibility :bust_in_silhouette:

#12773 Langauge names in own language do not use lang attribute
  CHANGELOG-WIP.md
  CHANGELOG.md
  src/controllers/UsersController.php
  src/templates/_includes/forms/selectize.twig
Labels: accessibility :bust_in_silhouette:

#12785 CSS font icon for search is not hidden from screen reader users
  CHANGELOG-WIP.md
  CHANGELOG.md
  src/templates/_elements/toolbar.twig
  src/web/assets/cp/dist/css/cp.css
  src/web/assets/cp/dist/css/cp.css.map
  src/web/assets/cp/src/css/_cp.scss
  src/web/assets/cp/src/css/_main.scss
Labels: accessibility :bust_in_silhouette:, ui :eyes:

#12792 Reintroduce asset/folder dragging
  CHANGELOG-WIP.md
  CHANGELOG.md
  packages/craftcms-sass/_mixins.scss
  src/models/VolumeFolder.php
  src/web/assets/cp/dist/cp.js
  src/web/assets/cp/dist/cp.js.map
  src/web/assets/cp/dist/css/cp.css
  src/web/assets/cp/dist/css/cp.css.map
  src/web/assets/cp/src/css/_cp.scss
  src/web/assets/cp/src/css/_fld.scss
  src/web/assets/cp/src/css/_main.scss
  src/web/assets/cp/src/js/AssetIndex.js
  src/web/assets/garnish/dist/garnish.js
  src/web/assets/garnish/dist/garnish.js.map
  src/web/assets/garnish/src/BaseDrag.js
  src/web/assets/garnish/src/Drag.js
Labels: assets :file_folder:

#12854 Do not use title as fallback for alt text
  CHANGELOG-WIP.md
  src/elements/Asset.php
Labels: accessibility :bust_in_silhouette:

#12961 Add visually-hidden headings to source nav and metadata container
  CHANGELOG-WIP.md
  src/base/Element.php
  src/templates/_layouts/elementindex.twig
  src/translations/en/app.php
Labels: accessibility :bust_in_silhouette:

#12963 Convert "list all tabs" menu in header to disclosure menu
  CHANGELOG-WIP.md
  src/templates/_includes/tabs.twig
  src/web/assets/cp/dist/cp.js
  src/web/assets/cp/dist/cp.js.map
  src/web/assets/cp/src/js/Tabs.js
Labels: accessibility :bust_in_silhouette:

#12941 Update `UniqueValidator` to support `filter` property
  CHANGELOG-WIP.md
  src/validators/UniqueValidator.php
  tests/unit/validators/UniqueValidatorTest.php
Labels: enhancement
